name: Release
on: [push]

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7' # Version range or exact version of a Python version to use, using semvers version range syntax.
      - name: build
        run: python setup.py sdist
      - name: List content
        run: tar -tvzf dist/`ls dist`
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@ae9c4b332a55c3ae8ba9d47fda1702d4cc7768b2
        with:
          user: __token__
          password: ${{ secrets.test_pypi_password }}
          repository_url: https://test.pypi.org/legacy/
